DROP TABLE IF EXISTS personal_records CASCADE;

CREATE TABLE personal_records(
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  squat SMALLINT NOT NULL,
  benchpress SMALLINT NOT NULL,
  deadlift SMALLINT NOT NULL,
  user_id INT REFERENCES users(id) ON DELETE CASCADE
);